HOS-4535
hostnet/phpcs-tool pull request #13
Opened 2017-03-16 14:56 UTC by AnwarElbo

2017-03-16 15:18 UTC, hboomsma requested changes

2017-03-16 15:18 UTC, hboomsma commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> + * This Sniff sniffs that all files examined have a @copyright notation + addes a fixer for those cases.
copy paste mistake

2017-03-16 15:18 UTC, hboomsma commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +        return \PHP_CodeSniffer_Tokens::$commentTokens;
please use T_DOC_COMMENT_TAG

2017-03-16 15:18 UTC, hboomsma commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                    $phpcs_file->fixer->replaceToken(
you can also insert a token before

2017-03-16 15:18 UTC, hboomsma commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                $error       = 'Comment refers to Covers annotation: Cover is missing first backslash';
covers annotation should use fully qualified class name (it should start with a \)

2017-03-16 15:18 UTC, hboomsma commented on test/Hostnet/Tests/Commenting/UnitTestCommentCoversUnitTest.php
> +
missing @covers

2017-03-16 15:18 UTC, hboomsma commented on test/Hostnet/Tests/Commenting/UnitTestCommentCoversUnitTest.php.0.inc
> +}
missing newline

2017-03-16 15:18 UTC, hboomsma commented on test/Hostnet/Tests/Commenting/UnitTestCommentCoversUnitTest.php.1.inc
> +}
missing newline

2017-03-16 15:18 UTC, hboomsma commented on test/Hostnet/Tests/Commenting/UnitTestCommentCoversUnitTest.php.0.inc
> +
please add
```php
// @covers not used here
```

and
```php
/**
 * @coversNothing
 */
```
and
```php
/**
 * @covers stdClass
 */
```
To your test set

2017-03-16 15:18 UTC, hboomsma commented on test/Hostnet/Tests/Commenting/UnitTestCommentCoversUnitTest.php.1.inc
> +<?php
redundant testcase, please remove

2017-03-16 15:18 UTC, hboomsma commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                $data        = [$comment_msg];
not needed

2017-03-16 15:18 UTC, hboomsma commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                $type        = 'SlashNotFound';
AtCoversNeedsFQCN

2017-03-16 15:18 UTC, hboomsma commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                if ($comment_msg !== '') {
it can not be empty, because then it is not a valid `@covers` statement (you do not need to match it in that case)

2017-03-16 15:18 UTC, hboomsma commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                    $type   = 'SlashNotFound';
redundant

2017-03-16 15:18 UTC, hboomsma commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                    $error .= '  "%s"';
could be in error message in the first place

2017-03-17 11:00 UTC, AnwarElbo commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> + * This Sniff sniffs that all files examined have a @copyright notation + addes a fixer for those cases.
Fixed

2017-03-17 11:00 UTC, AnwarElbo commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +        return \PHP_CodeSniffer_Tokens::$commentTokens;
Fixed

2017-03-17 11:00 UTC, AnwarElbo commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                $type        = 'SlashNotFound';
Fixed

2017-03-17 11:01 UTC, AnwarElbo commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                $error       = 'Comment refers to Covers annotation: Cover is missing first backslash';
Fixed

2017-03-17 11:01 UTC, AnwarElbo commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                $data        = [$comment_msg];
Fixed

2017-03-17 11:02 UTC, AnwarElbo commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                if ($comment_msg !== '') {
Fixed (was from a copy paste)

2017-03-17 11:02 UTC, AnwarElbo commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                    $type   = 'SlashNotFound';
Fixed

2017-03-17 11:02 UTC, AnwarElbo commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                    $error .= '  "%s"';
Fixed

2017-03-17 11:02 UTC, AnwarElbo commented on src/Hostnet/Sniffs/Commenting/UnitTestCommentCoversSniff.php
> +                    $phpcs_file->fixer->replaceToken(
Fixed

2017-03-17 11:02 UTC, AnwarElbo commented on test/Hostnet/Tests/Commenting/UnitTestCommentCoversUnitTest.php
> +
Fixed

2017-03-17 11:02 UTC, AnwarElbo commented on test/Hostnet/Tests/Commenting/UnitTestCommentCoversUnitTest.php.0.inc
> +
Fixed

2017-03-17 11:03 UTC, AnwarElbo commented on test/Hostnet/Tests/Commenting/UnitTestCommentCoversUnitTest.php.0.inc
> +}
Fixed

2017-03-17 11:03 UTC, AnwarElbo commented on test/Hostnet/Tests/Commenting/UnitTestCommentCoversUnitTest.php.1.inc
> +<?php
Fixed (changed it so it is useful this time)

2017-03-17 11:04 UTC, AnwarElbo commented on test/Hostnet/Tests/Commenting/UnitTestCommentCoversUnitTest.php.1.inc
> +}
Fixed

2017-03-17 13:55 UTC, hboomsma approved these changes

2017-03-17 13:57 UTC, merged